### ISSUE TITLE
Add homepage option to software

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit-site#1]
As suggested by @bhaller, as https://messerlab.org/slim/ is a natural homepage for SLiM. Change SLiMs doc link to http://benhaller.com/slim/SLiM_Manual.pdf

**Comment by bhaller** [comment]
If you wanted to avoid hard-coding this, it is given as the "Website" property in the GitHub repo for SLiM; maybe that ought to be the standard place to pull a home page for each project from (if any).

**Comment by benjeffery** [comment]
Great idea! Forgot that was in the github API!
