### ISSUE TITLE
Final tweaks

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit-site#109]
- [x] Remove rock-solid
- [x] fwdpy11 and rust examples
- [x] Grep for Todo
- [x] White background on blog images
- [x] Dangling commas on community
- [x] Twitter tags
- [x] Note "how to add a project to this page"

**Comment by jeromekelleher** [comment]
SGTM.

**Comment by benjeffery** [comment]
All these are done now. Twitter card seems to work, and can be tested by pasting a URL in the twitter compose box.
