### ISSUE TITLE
Trivial extra links

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit-site#126]
Since https://tskit.dev/tskit/docs/stable/introduction.html goes to the docs, I was expecting https://tskit.dev/tskit/ to return a useful page about tskit. Instead it is a 404, and I had to hunt around to find was https://tskit.dev/software/tskit.html. Perhaps `https://tskit.dev/tskit/ ` should simply redirect to that software page?

**Comment by jeromekelleher** [comment]
This would be handy
