### ISSUE TITLE
SVG images?

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit-site#14]
Should I display TS images on the website using SVG, or use some bitmap format instead?

https://caniuse.com/?search=svg

Suggests SVG support in 99.15% of internet users.

**Comment by jeromekelleher** [comment]
Seems fine to use SVG to me, but I don't know much about the browser ecosystem.

**Comment by benjeffery** [comment]
SVG is preferred to png for everything except photos.The site already uses them.
