### ISSUE TITLE
Link to videos

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit-site#143]
Is there a way to link from a page such as `genetics_resources.html` to a specific resource card such as a video (e.g. either via a named anchor or if there is a separate hidden mini-page for each resource card), or do we have to embed the video instead?

I mention because although we don't have an "introduction to statgen " tutorial yet, we could possibly link to Wilder's talk as a stop-gap measure. I expect this ability might be useful elsewhere too.

**Comment by benjeffery** [comment]
No, you can't. Even if there was an anchor, it wouldn't highlight the resource. As the resources as mainly links, probably linking directly will be best elsewhere.

**Comment by hyanwong** [comment]
I see what you mean about not highlighting the resource. I do hanker after being able to say, e.g. in a tutorial "See [this video] by Wilder Wohns for an in-depth explanation", and I feel it would be nice to link to something on the tskit website (where a single link to the video can be maintained and updated if necessary), rather than linking directly to YouTube or Vimeo.
