### ISSUE TITLE
Confusing behaviour of navbar links

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit-site#151]
A really minor thing, but it keeps bugging me. If I click on e.g. python-api.html#treesequence-api, the right
hand navbar doesn't expand the "TreeSequence API" section to show the various subcategories within that section. Instead, I have to scroll down a fraction to get the navbar to show the subcategories in that section.

This means that e.g. clicking on the link in the navbar doesn't expand the section, as you might hope. In fact, when you click on one of those navbar links, the *previous* topic is expanded, which is really confusing.

E.g. here's the result I get when clicking on "Tables and Table Collections" in the navbar (it looks like `Tree API->Export` is highlighted, because that's the subsubsection before the "Tables and Table Collections" heading).

<img width="1031" alt="Screenshot 2022-11-17 at 18 32 25" src="https://user-images.githubusercontent.com/4699014/202529252-29bd6b4f-ea4c-41a7-9f9d-52e769512930.png">

**Comment by benjeffery** [comment]
I think this might get fixed if I pull in the upstream changes from `sphinx-book-theme`.

**Comment by hyanwong** [comment]
Oh, that would be good, thanks. It's a minor thing, but bugs me a lot!

**Comment by hyanwong** [comment]
> I think this might get fixed if I pull in the upstream changes from sphinx-book-theme.

Did you manage to see if this fixed the problem @benjeffery ?

**Comment by daikitag** [comment]
It seems that it is a bug from the previous version of `sphinx-book-theme`, and they have fixed it in their new release.
https://github.com/executablebooks/sphinx-book-theme/pull/677
However, I think it is impossible for me to do a pull request without modifying the overall structure of tskit website, as 100+ flies are being changed.

**Comment by benjeffery** [comment]
Ah good, have they re-organised their CSS though? Might be easier just to port across the fix.

**Comment by daikitag** [comment]
It seems that they had fixed their CSS as well, but 100+ files were changed compared with the version that you used to build `tskit-book-theme`. Do you think you can successfully merge their current version to `tskit-book-theme? I can try changing it, but I think it would be difficult for me, as I'm not sure about which files you had modified from `sphix-book-theme`.

**Comment by benjeffery** [comment]
This still seems to happen, when using the latest docs that use `sphinx-book-theme` directly. I'll keep updating as they release, and it might get fixed, but I'm closing here as there is nothing we can do.
