### ISSUE TITLE
Additional "utility projects"

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit-site#159]
We should add `tszip` and (possibly) `tsconvert` to the list of projects, if only so I can hotlink to documentation for `tszip.decompress`.

**Comment by benjeffery** [comment]
A section after "Ecosystem projects" might make sense for these smaller things?

**Comment by hyanwong** [comment]
Yeah, that's the sort of thing I was thinking.

**Comment by jeromekelleher** [comment]
I think we can add tszip to the list of top level projects - it's a fully documented and supported utility. 

Not so clear we want to advertise tsconvert here though.
