### ISSUE TITLE
latest software link to pyslim out of date

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/tskit-site#174]
It shows
> Latest release: 1.0b1 11 months and 2 weeks ago 
but the latest is 1.1

This is a placeholder

**Comment by benjeffery** [comment]
The site isn't building at the moment due to tsinfer docs failing. Once that is fixed everything will update.

**Comment by benjeffery** [comment]
The site is now working, but a github release needs to be created for the correct version to show.

**Comment by petrelharp** [comment]
Ah! Yet another step for the release checklist.
