### ISSUE TITLE
Publications out of date

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit-site#211]
There's been quite a few relevant publications since the Unified genealogy paper (which is the last). Here's some I've been involved in. Any others?

- ARG paper: https://doi.org/10.1093/genetics/iyae100
- tstrait: https://doi.org/10.1093/bioinformatics/btae334
- link-ancestors: https://doi.org/10.1093/bioadv/vbad163
- Quebec pedigree sims: https://doi.org/10.1126/science.add5300
- msprime 1.0: https://doi.org/10.1093/genetics/iyab229

**Comment by hyanwong** [comment]
Ah yes, a number of these have been added to the `_news` items, but not as publications in `[_resources](https://github.com/tskit-dev/tskit-site/tree/main/_resources)`. We could probably just trim down the news items and sick those in.
