### ISSUE TITLE
Wrong version displayed for msprime

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit-site#22]
The wrong version of msprime is being displayed on the [intro page](https://tskit.dev/msprime/docs/latest/intro.html). For some reason, we've got version = "0.1.dev1", which means that either the custom sphinx extension defined in https://github.com/tskit-dev/msprime/pull/1408 isn't being executed, or the sphinx config is somehow being overwritten later in the process.

The Python path must be OK, because we wouldn't get the autodocs output otherwise.

Any ideas @benjeffery?

**Comment by benjeffery** [comment]
Odd, I can't recreate locally. I think we should use a more flexible way of getting the version number in anyway as I suggested over at https://github.com/tskit-dev/msprime/issues/1396#issuecomment-768208935

**Comment by jeromekelleher** [comment]
Happy to look at alternatives to setting the version via sphinx.

**Comment by jeromekelleher** [comment]
Maybe it's an issue with running in a venv? But, you always run everything in venvs, don't you? (So you should see it locally if so...)

**Comment by benjeffery** [comment]
Yes, I'm always in a venv, I even wiped my venv and pip installed the CI-docs requirements, still couldn't recreate.

**Comment by jeromekelleher** [comment]
Weird. A snippet of JS would be more flexible, allright, if we could do that.

**Comment by jeromekelleher** [comment]
Looks like this is a problem with shallow clones done on Actions:

- https://github.com/pypa/setuptools_scm/issues/414
- https://github.com/pypa/setuptools_scm/issues/480

I'll try the ``fetch-depth: 0`` fix and see how it goes.
