### ISSUE TITLE
add pyslim

### ISSUE THREAD

**Issue by mufernando** [tskit-dev/tskit-site#38]
Add pyslim to the tools powered by tree sequences.

**Comment by petrelharp** [comment]
Ok, we're ready for this! Help would be greatly appreciated.

**Comment by benjeffery** [comment]
All you need to do is add a file to the `_software` directory, following the format of the others there. https://raw.githubusercontent.com/tskit-dev/tskit-site/main/_software/1-msprime.md is probably the most complete example.
