### ISSUE TITLE
Make a tskit favicon

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tskit-site#47]
I guess that would be nice for the tskit.dev site? Maybe just a 3-tip tree in the logo colours.

**Comment by benjeffery** [comment]
https://emoji.slack-edge.com/T01017W5DP0/tskit/21c5b069e8c066d8.png is too big I guess.

**Comment by hyanwong** [comment]
> https://emoji.slack-edge.com/T01017W5DP0/tskit/21c5b069e8c066d8.png is too big I guess.

Probably? What do you think?

**Comment by benjeffery** [comment]
Yeah, I think a 3-tip tree would be good as you say.

**Comment by hyanwong** [comment]
How's this @benjeffery ?


[tskit_fav.svg.zip](https://github.com/tskit-dev/tskit-site/files/6623830/tskit_fav.svg.zip)

**Comment by benjeffery** [comment]
Great!

**Comment by hyanwong** [comment]
Closed in favour of #93
