### ISSUE TITLE
Brief for hired help 

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit-site#60]
We're considering paying for some work to polish the design of https://tskit.dev, so will need a brief:

tskit.dev is the central hub for open-source tree-sequence related software and research.

**Goals:**
- Give an overview of tree sequences and their uses
- Act as a resource hub, linking or hosting (as appropriate) documentation, code, release notes, tutorials, talks, videos and papers. Make these resources as "discoverable" as possible.
- Encourage new contributors, indicate that development is free and open and active.
- Signpost ways to connect with and get support from the community via issues and discussions.
- Have a design looks professional, solid and readable on desktop and mobile

**Current technical implementation:**
Jekyll (Ruby) with custom plugins and theme, deployed using github actions to github pages. Not looking to change/rewrite this unless necessary. We'd like changes to be via github PRs. All development of tskit.dev is open and under the MIT license.

**Specified improvements we'd like:**
- Design is a rough outline and needs polishing, should integrate well with the JupyterBook documentation sites, so that there's a consistent look and feel throughout.
- Make site design responsive so that it works on mobile and desktop.
- All images are placeholders and need replacing.
- Software logos for tskit, msprime and tsdate to be made consistent and a logo to be made for tsinfer.
- SEO pass needed, along with meta tags for things like twitter previews.
- We're mostly happy with how the information is organised, but open to suggestions of improvement.

**Comment by benjeffery** [comment]
@jeromekelleher @petrelharp anything to add?

**Comment by petrelharp** [comment]
Sounds good! I'd just add "making discoverable" or something to the second point (the "resource hub" one). I don't know if there's any SEO to do (like, do we need keywords in the html head or something? I don't know how this works these days...)

**Comment by benjeffery** [comment]
Good point - I've edited to that effect.

**Comment by jeromekelleher** [comment]
I would add "Integrate well with the JupyterBook documentation sites, so that there's a consistent look and feel throughout"

So, not necessarily do much with the JupyterBook themes, but to maybe borrow some of the design language from JupyterBook.

**Comment by benjeffery** [comment]
Great, edited to that effect, also added a point about developing on github. I think this is enough to start getting some quotes.

**Comment by benjeffery** [comment]
I've tightened up the language a little to be more specific on the deliverables. The university requires that I also send along a form as part of it's tender process:
[170511_Request_for_Proposal_v2_0.doc.zip](https://github.com/tskit-dev/tskit-site/files/6868124/170511_Request_for_Proposal_v2_0.doc.zip)

I'm now going to contact the 3 preferred suppliers on the university list.

**Comment by jeromekelleher** [comment]
Thanks for doing that - looks like fun...

**Comment by benjeffery** [comment]
An update for those following - I have had a response from some of the three companies on the universities preferred list and are talking to them about possible work.

**Comment by hyanwong** [comment]
Great. I'm sure this is on the agenda (e.g. https://github.com/tskit-dev/tskit-site/issues/3) but I've been reading the site on my (small) mobile, and it doesn't look terribly good:

![tskit dev  The open source tree sequence community](https://user-images.githubusercontent.com/4699014/128508716-e0a9128c-747d-46e1-9ee0-166bbc16f197.png)

**Comment by hyanwong** [comment]
Can we close this now @benjeffery ?

**Comment by benjeffery** [comment]
Yes! Thanks!
