### ISSUE TITLE
tskit version not rendering

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit-site#63]
We're seeing ``tskit __TSKIT_VERSION__`` in the jupyterbook code. Probably a very simple fix, mimicing the mpsrime setup

**Comment by benjeffery** [comment]
Reopening as that PR hasn't done the trick.

**Comment by grahamgower** [comment]
FYI, you might consider a different approach to getting the version into jupyter-book. I've just experimented with adding a local sphinx extension for this, and it's working for demesdraw.
https://github.com/grahamgower/demesdraw/blob/main/docs/_config.yml#L31-L33
https://github.com/grahamgower/demesdraw/blob/main/docs/_ext/inject_version.py

**Comment by benjeffery** [comment]
Problem was on tskit's side, fixed now.

**Comment by benjeffery** [comment]
> FYI, you might consider a different approach to getting the version into jupyter-book.

That's nice, and much cleaner. We should use that.
