### ISSUE TITLE
Builds not getting triggered by docs repos

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit-site#66]
Events on the msprime repo don't seem to be triggering builds here - I've had to manually trigger builds to update the msprime docs.

Possible the same for tskit?

**Comment by jeromekelleher** [comment]
Is this still an issue @benjeffery? I'm not sure what's going on, builds seem to be getting triggered now OK.

**Comment by benjeffery** [comment]
I'm not sure why this stopped for a while, if things are working now I'll close this, open if any more trouble.
