### ISSUE TITLE
Add blog/announcments/... section

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit-site#68]
@hyanwong and I have been discussing the idea of having a "blog" in which we can have pages to do quick examples. For example, it would be great to do a "What's new in tskit 0.4.0" post based on @benjeffery's notebook from a few weeks ago. After some discussion, we think it's probably best to not be dynamic, so that the content stays the same over time.

Nothing fancy required really, just markdown input, and the ability to convert Jupyter notebooks into something that looks OK in the final version.

Any thoughts?

**Comment by hyanwong** [comment]
This would also be a nice place to point people to from e.g. a twitter thread, and it's quicker and easier than waiting for a paper to be published.

I think the key thing it to make it easy for someone to take work they have already done (e.g. an email announcement, a notebook prepared for a TS meeting, text from a slide deck etc) and turn it into a "post" in a handful of minutes.

It might be useful to have some ideas of "posts" which could be placed here. Here are some ideas which could be used to pre-populate posts. Here are my thoughts about the sort of thing that might work:

- @benjeffery's "introducing tskit 0.4 to tskit devs" notebook
- @jeromekelleher's "introducing msprime 1.0 to tskit devs" notebook (I think it's a notebook)
- @molpopgen's "introducing tskit rust to devs" presentation (was this a notebook, I can't remember)
- A summary of @petrelharp 's paper on the duality of branch length & site stats
- A summary of the "Ancestry of everyone" Nature Genetics paper (or perhaps something similar focussed on `tsinfer`)
- A summary of the "Unified genealogy" paper, if it gets accepted (or perhaps even for the preprint?)
- Major SLiM releases?
- Something from @awohns for the initial `tsdate` release?

Like most blog posts, it would be nice (if not strictly necessary) to have a picture accompanying the post. This could be as simple as a photo of the person doing the announcement, or a logo, or a picture of a tree sequence, or whatever.

**Comment by benjeffery** [comment]
Sounds good, I'll add this into the ongoing design work.

**Comment by jeromekelleher** [comment]
I wonder if we could get something simple working fairly soon, so that we have some example content in place for the redesign? It would be great to have an "tskit 0.4.0" announcement page to point to (the changelog is too terse to be meaningful to most people).

**Comment by molpopgen** [comment]
I will be rewriting my intro shortly.  I've procrastinated somewhat because @benjeffery may freak out due to the dependencies. 😝 The rust notebook kernel is not small.

**Comment by benjeffery** [comment]
> I will be rewriting my intro shortly. I've procrastinated somewhat because @benjeffery may freak out due to the dependencies. stuck_out_tongue_closed_eyes The rust notebook kernel is not small.

For the blog we are using notebook markdown, as they are static. The docs are dynamic and compiled on each deploy, I don't think rust will be an issue, we can cache stuff.

**Comment by benjeffery** [comment]
Done in the redesign!
