### ISSUE TITLE
tskit build broken

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit-site#70]
Needs an update to fix C deps on compiling the python modulel

**Comment by jeromekelleher** [comment]
I see what the issue is - it's trying to build the stable tag which requires a different repo structure. Maybe a judicious ``git submodule update`` would sort it out for now @benjeffery?

**Comment by jeromekelleher** [comment]
Nice to get #63 fixed as well as we're fiddling with it.

**Comment by benjeffery** [comment]
Ok, will do this when I next get to work.

**Comment by jeromekelleher** [comment]
Sure, no hurry.

**Comment by benjeffery** [comment]
Fixed by #71

**Comment by hyanwong** [comment]
Thanks for fixing this @benjeffery. Much appreciated
