### ISSUE TITLE
Deploy tskit/tutorials here

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/tskit-site#8]
We'd like to deploy the HTML for https://github.com/tskit-dev/tutorials here at the stable URL tskit.dev/tutorials

As a way of avoiding rebuilding the docs locally (and the complexity that does with it) perhaps we could pull in the gh-pages branch? This would be quick and simple, and be a reasonable thing to run on a cron job. Could do the same thing for the msprime docs?

**Comment by benjeffery** [comment]
My thinking with building the msprime docs here was that we want to build multiple versions, and possibly have some influence over the build process (e.g. inserting dev version warning banners). I'm planning on caching the doc build by msprime commit hash, so I'm not concerned about build time. As you say the only downside is the complexity of recreating the build process here.

As the tutorials are single versioned and not modified this is less of a concern, so I probably will pull in `gh-pages`.

**Comment by jeromekelleher** [comment]
This is done.
