### ISSUE TITLE
Text for "Genetics Research" page.

### ISSUE THREAD

**Issue by benjeffery** [tskit-dev/tskit-site#88]

**Comment by benjeffery** [comment]
I've done a very basic job here in a5a47c6, I'm hoping @hyanwong can sparkle some magic prose over this on his return.

**Comment by hyanwong** [comment]
Happy to have a go. How do you want me to do this: if you merge https://github.com/tskit-dev/tskit-site/commit/a5a47c65821570ca888ccfa57ac70c918687d306 then I can PR adjustments to the file if you like, @benjeffery ?

**Comment by benjeffery** [comment]
Can you do PR's against the `revamp` branch on the `benjeffery/tskit-site` fork?

**Comment by hyanwong** [comment]
Is the current (new) text too dense, or can this issue be closed?

**Comment by benjeffery** [comment]
It looks fine to me, worth using a few extra words to get the point across.
